### ISSUE TITLE
running into errors on build script

### ISSUE THREAD

**Issue by xxdesmus** [wmetcalf/buildcuckoo-trusty#1]
Trusty VPS (DigitalOcean). Should the only steps be to clone the repo and run buildworld.sh ? 

If so, when I run --> buildworld.sh  I get to this part of the build script --> 

```
sudo virsh net-destroy default
 sudo virsh net-undefine default
 sudo service libvirtd restart

 echo "#!/bin/sh
 su cuckoo -c \"/usr/local/bin/ruleupdates.sh\" && /etc/init.d/suricata restart" | sudo tee /etc/cron.daily/ruleupdates
sudo chmod +x /etc/cron.daily/ruleupdates
```

but then it bombs out and I get this error message -->

```
.....{OUTPUT ABOVE HERE}.......
Setting up virtualbox-4.3 (4.3.12-93733~Ubuntu~raring) ...
Adding group `vboxusers' (GID 120) ...
Done.
Stopping VirtualBox kernel modules ...done.
Uninstalling old VirtualBox DKMS kernel modules ...done.
Trying to register the VirtualBox kernel modules using DKMS ...done.
Starting VirtualBox kernel modules ...done.
Processing triggers for libc-bin (2.19-0ubuntu6) ...
Processing triggers for ureadahead (0.100.0-16) ...
 * Stopping RDP Session manager
   ...done.
 * Starting Remote Desktop Protocol server
   ...done.
Network default destroyed

Network default has been undefined

libvirtd: unrecognized service
#!/bin/sh
su cuckoo -c "/usr/local/bin/ruleupdates.sh" && /etc/init.d/suricata restart
```

if I manually run `su cuckoo -c "/usr/local/bin/ruleupdates.sh" && /etc/init.d/suricata restart`  I get  `No passwd entry for user 'cuckoo'`

If I try to set the password for user cuckoo with `passwd cuckoo` it tells me `passwd: user 'cuckoo' does not exist`  and if I manually add the cuckoo user and re-run the entire script it'll still bomb out at the same point.

Am I doing something wrong?

**Comment by GroteVriendelijkeReus** [comment]
This might be an old topic, but running the script clean out-of-the-box, provides exactly the same error.

Should i add a password to the cuckoo user or just make sure that user can't login?
